openapi: 3.0.0
info:
  description: >-
    Starter Project for building REST API Microservices using Node.js and
    Express
  license:
    name: UNLICENSED
  title: node-api-svc-starter
  version: 0.0.1
servers:
  - url: "http://localhost:3100/"
  - url: "https://localhost:3100/"
paths:
  /healthcheck:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  currentTime:
                    example: "2020-05-30T16:07:59.840Z"
                    type: string
                  name:
                    example: API Micro-Service
                    type: string
                  started:
                    example: "2020-05-30T16:07:59.695Z"
                    type: string
                  status:
                    example: Ready
                    type: string
                  uptime:
                    example: 0.145
                    type: number
                  version:
                    example: "0.0"
                    type: string
                type: object
          description: OK
        "500":
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: Failed to retrieve healthcheck status
                    type: string
                type: object
          description: Internal Server Error
      summary: /healthcheck
  /v1/contracts:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  properties:
                    CONTRACT_ID:
                      type: string
                    CONTRACT_NAME:
                      type: string
                    CONTRACT_STATUS:
                      type: string
                    JOINT_VENTURE_FLAG:
                      type: string
                  type: object
                type: array
          description: OK
        "400":
          content:
            application/json:
              schema:
                properties:
                  code:
                    example: 400
                    type: number
                  errors:
                    example:
                      - contract_status: '"contract_status" must be one of [A, W]'
                    items:
                      properties:
                        contract_status:
                          type: string
                      type: object
                    type: array
                  message:
                    example: Validation Failed
                    type: string
                type: object
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                properties:
                  error:
                    example: Anonymous access prohibited
                    type: string
                type: object
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: Failed to fetch ECM Contracts
                    type: string
                type: object
          description: Internal Server Error
      summary: /v1/contracts
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  properties:
                    CONTRACT_ID:
                      type: string
                    CONTRACT_NAME:
                      type: string
                    CONTRACT_STATUS:
                      type: string
                    JOINT_VENTURE_FLAG:
                      type: string
                  type: object
                type: array
          description: OK
        "400":
          content:
            application/json:
              schema:
                properties:
                  code:
                    example: 400
                    type: number
                  errors:
                    example:
                      - contract_status: '"contract_status" is not allowed'
                    items:
                      properties:
                        contract_status:
                          type: string
                      required:
                        - contract_status
                      type: object
                    type: array
                  message:
                    example: Validation Failed
                    type: string
                type: object
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                properties:
                  error:
                    example: Anonymous access prohibited
                    type: string
                type: object
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: Failed to fetch ECM Contracts
                    type: string
                type: object
          description: Internal Server Error
      summary: /v1/contracts
  /v1/contracts-alt:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  properties:
                    CONTRACT_ID:
                      type: string
                    CONTRACT_NAME:
                      type: string
                    CONTRACT_STATUS:
                      type: string
                    JOINT_VENTURE_FLAG:
                      type: string
                  type: object
                type: array
          description: OK
        "400":
          content:
            application/json:
              schema:
                properties:
                  code:
                    example: 400
                    type: number
                  errors:
                    example:
                      - contract_status: '"contract_status" must be one of [A, W]'
                    items:
                      properties:
                        contract_status:
                          type: string
                      type: object
                    type: array
                  message:
                    example: Validation Failed
                    type: string
                type: object
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                properties:
                  error:
                    example: Anonymous access prohibited
                    type: string
                type: object
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: Failed to fetch ECM Contracts
                    type: string
                type: object
          description: Internal Server Error
      summary: /v1/contracts-alt
  /v1/oec-stats:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  properties:
                    CNTRCT_ID:
                      type: string
                    CNTRCT_YEAR:
                      type: string
                    CREATD_BY:
                      type: string
                    CREATD_DT:
                      type: string
                    DLNQNT_ENRLMTS:
                      type: number
                    ENRLMT_DWNLDED:
                      type: number
                    ENRLMT_FIL_DT:
                      type: string
                    ENRLMT_NOT_DWNLDED:
                      type: number
                    LAST_UPDTD_BY:
                      type: string
                    LAST_UPDTD_DT:
                      type: string
                  type: object
                type: array
          description: OK
        "400":
          content:
            application/json:
              schema:
                properties:
                  code:
                    example: 400
                    type: number
                  errors:
                    example:
                      - contract_status: '"contract_status" must be one of [A, W]'
                    items:
                      properties:
                        contract_status:
                          type: string
                      type: object
                    type: array
                  message:
                    example: Validation Failed
                    type: string
                type: object
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                properties:
                  error:
                    example: Anonymous access prohibited
                    type: string
                type: object
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: Failed to fetch OEC stats
                    type: string
                type: object
          description: Internal Server Error
      summary: /v1/oec-stats
  /v1/service-categories:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  properties:
                    ADDLDESCRIPTION:
                      type: string
                    DESCRIPTION:
                      type: string
                    SERVICE_CATEGORY_ID:
                      type: string
                    SUBCATEGORY:
                      type: string
                    TITLE:
                      type: string
                  type: object
                type: array
          description: OK
        "400":
          content:
            application/json:
              schema:
                properties:
                  code:
                    example: 400
                    type: number
                  errors:
                    example:
                      - contract_status: '"contract_status" must be one of [A, W]'
                    items:
                      properties:
                        contract_status:
                          type: string
                      type: object
                    type: array
                  message:
                    example: Validation Failed
                    type: string
                type: object
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                properties:
                  error:
                    example: Anonymous access prohibited
                    type: string
                type: object
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                properties:
                  message:
                    example: Failed to fetch service categories
                    type: string
                type: object
          description: Internal Server Error
      summary: /v1/service-categories
components:
  securitySchemes:
    JWT:
      in: header
      name: Authorization
      type: apiKey
security:
  - JWT: []
